package com.github.veselinazatchepina.alarmclock

const val NOTIFICATION_WORK_REQUEST_ID = "WORK_REQUEST_ID"
const val NOTIFICATION_ACTION_TYPE = "ACTION_TYPE"
const val NOTIFICATION_ALARM_CLOCK_ID = 31
const val NOTIFICATION_ALARM_DAYS = "NOTIFICATION_ALARM_DAYS"
const val NOTIFICATION_ALARM_HOURS = "NOTIFICATION_ALARM_HOURS"
const val NOTIFICATION_ALARM_MINUTES = "NOTIFICATION_ALARM_MINUTES"

const val ALARM_CLOCK_WORK_REQUEST_ID = "ALARM_CLOCK_WORK_REQUEST_ID"
const val ALARM_CLOCK_ALARM_DAYS = "ALARM_CLOCK_ALARM_DAYS"
const val ALARM_CLOCK_ALARM_HOURS = "ALARM_CLOCK_ALARM_HOURS"
const val ALARM_CLOCK_ALARM_MINUTES = "ALARM_CLOCK_ALARM_MINUTES"