package com.github.veselinazatchepina.alarmclock

const val NOTIFICATION_ACTION_TYPE = "ACTION_TYPE"
const val NOTIFICATION_ALARM_CLOCK_ID = 31
const val NOTIFICATION_ALARM_DAYS = "NOTIFICATION_ALARM_DAYS"
const val NOTIFICATION_ALARM_TIME_MILLIS = "NOTIFICATION_ALARM_TIME_MILLIS"

const val ALARM_CLOCK_ALARM_DAYS = "ALARM_CLOCK_ALARM_DAYS"
const val ALARM_CLOCK_TIME_MILLIS = "ALARM_CLOCK_TIME_MILLIS"

const val HOURS_MAX_VALUE = 24
const val MINUTES_MAX_VALUE = 60

const val SNOOZE_MINUTES_COUNT = 5

const val ALARM_CLOCK_RINGING_TIME_MINUTES = 1